Profile: EEVRISPatientChildUnknownId
Parent: EEMPIPatient
Id: ee-vris-patient-child-unknown-id
Title: "Patient: EE VRIS Child"
Description: "Child born from VRIS fertility treatment with UNKNOWN ID (and NO name) Identifier is generated by HC provider. (ee VRIS viljatusravi tulemusena sündinud laps. ISIKUKOOD teadMATA! IK genereeritud TTO poolt.)"
* ^status = #draft

* extension contains
    $birth-place named birthPlace 0..1
* extension[birthPlace] ^short = "(ee Lapse sünniriik / sünnikoht. Kui teadmata siis tühjaks jätta)"

* identifier ^short = "(ee Kasutada systemina https://fhir.ee/sid/pid/est/prn, Nimeruum TTO poolt genereeritud identifikaatoritele)"
* gender 1..1
* gender ^short = "(ee Lapse sugu)"
* birthDate 0..1
* deceasedDateTime ^short = "(ee Lapse surma kuupäev, Surmaregistrist)"

* link 0..*
* link.other only Reference(EEVRISPatientChild)
* link.other ^short = "(ee Juhul kui isikukood selgub, siis saab siit kaudu ühendada kaks lapse ressurssi link-operatsiooni abil)"
//* link.type = #seealso